'use client';
import { useCallback, useEffect, useState } from 'react';
import { Wallet, Plus, Download, BadgeCheck, Settings2 } from 'lucide-react';
import PageHeader from '@/components/PageHeader';
import Loader from '@/components/Loader';
import Modal from '@/components/Modal';
import { EmptyState, StatusBadge } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { money } from '@/lib/format';
import { payroll as payApi, employees as empApi } from '@/lib/db';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function PayrollPage() {
  const { user } = useAuth();
  const canManage = ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR'].includes(user?.role);
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [genOpen, setGenOpen] = useState(false);
  const [structOpen, setStructOpen] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try { const list = await payApi.list(); setItems(list); }
    catch { /* ignore */ } finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const download = (p) => {
    const fmt = (n) => `${p.currency || 'USD'} ${Number(n || 0).toLocaleString()}`;
    const name = `${p.employee?.firstName || ''} ${p.employee?.lastName || ''}`.trim();
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>Payslip ${p.employee?.employeeId} ${p.month}/${p.year}</title>
      <style>body{font-family:system-ui,Arial,sans-serif;color:#0f172a;max-width:680px;margin:32px auto;padding:0 16px}
      h1{font-size:20px;margin:0 0 4px}.muted{color:#64748b;font-size:13px}
      table{width:100%;border-collapse:collapse;margin-top:20px;font-size:14px}
      td,th{padding:8px 10px;border-bottom:1px solid #e2e8f0;text-align:left}
      .r{text-align:right}.tot{font-weight:700;font-size:16px}
      .hd{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #1f49f5;padding-bottom:12px}</style></head>
      <body><div class="hd"><div><h1>Payslip</h1><div class="muted">${MONTHS[p.month - 1]} ${p.year}</div></div>
      <div class="muted r">${name}<br/>${p.employee?.employeeId || ''}<br/>Status: ${p.status}</div></div>
      <table><tr><th>Earnings</th><th class="r">Amount</th></tr>
      <tr><td>Gross</td><td class="r">${fmt(p.gross)}</td></tr>
      <tr><td>Tax</td><td class="r">- ${fmt(p.tax)}</td></tr>
      <tr class="tot"><td>Net pay</td><td class="r">${fmt(p.netPay)}</td></tr></table>
      <p class="muted" style="margin-top:24px">Generated by HRMS · This is a system-generated payslip. Use your browser's “Save as PDF”.</p>
      <script>window.onload=()=>window.print()</script></body></html>`;
    const w = window.open('', '_blank');
    if (!w) { alert('Allow pop-ups to view the payslip.'); return; }
    w.document.write(html); w.document.close();
  };

  const markPaid = async (p) => {
    try { await payApi.markPaid(p._id); load(); }
    catch (e) { alert(e.message || 'Action failed'); }
  };

  return (
    <>
      <PageHeader title="Payroll" subtitle="Generate runs, manage salary structures, and issue payslips"
        actions={canManage && (
          <div className="flex gap-2">
            <button className="btn-outline" onClick={() => setStructOpen(true)}><Settings2 size={16} /> Salary structure</button>
            <button className="btn-primary" onClick={() => setGenOpen(true)}><Plus size={16} /> Generate payroll</button>
          </div>
        )} />

      {loading ? <Loader /> : items.length === 0 ? (
        <EmptyState icon={Wallet} title="No payroll runs yet" hint={canManage ? 'Set a salary structure, then generate your first run.' : 'Your payslips will appear here.'}
          action={canManage && <button className="btn-primary" onClick={() => setGenOpen(true)}><Plus size={16} /> Generate payroll</button>} />
      ) : (
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead><tr className="border-b text-left text-slate-400">
                <th className="px-5 py-3 font-medium">Employee</th><th className="px-5 py-3 font-medium">Period</th>
                <th className="px-5 py-3 font-medium">Gross</th><th className="px-5 py-3 font-medium">Tax</th>
                <th className="px-5 py-3 font-medium">Net pay</th><th className="px-5 py-3 font-medium">Status</th>
                <th className="px-5 py-3 font-medium text-right">Actions</th>
              </tr></thead>
              <tbody>
                {items.map((p) => (
                  <tr key={p._id} className="border-b last:border-0">
                    <td className="px-5 py-3 font-medium">{p.employee?.firstName} {p.employee?.lastName} <span className="text-xs text-slate-400">({p.employee?.employeeId})</span></td>
                    <td className="px-5 py-3 text-slate-500">{MONTHS[p.month - 1]} {p.year}</td>
                    <td className="px-5 py-3">{money(p.gross, p.currency)}</td>
                    <td className="px-5 py-3 text-slate-500">{money(p.tax, p.currency)}</td>
                    <td className="px-5 py-3 font-semibold">{money(p.netPay, p.currency)}</td>
                    <td className="px-5 py-3"><StatusBadge status={p.status} /></td>
                    <td className="px-5 py-3">
                      <div className="flex justify-end gap-1">
                        <button className="btn-ghost p-1.5" title="Download payslip" onClick={() => download(p)}><Download size={16} /></button>
                        {canManage && p.status !== 'PAID' && <button className="btn-ghost p-1.5 text-emerald-600" title="Mark paid" onClick={() => markPaid(p)}><BadgeCheck size={16} /></button>}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {genOpen && <GeneratePayroll onClose={() => setGenOpen(false)} onSaved={() => { setGenOpen(false); load(); }} />}
      {structOpen && <StructureEditor onClose={() => setStructOpen(false)} />}
    </>
  );
}

function useEmployees() {
  const [employees, setEmployees] = useState([]);
  useEffect(() => { empApi.list({ limit: 100 }).then((r) => setEmployees(r.items)).catch(() => {}); }, []);
  return employees;
}

function GeneratePayroll({ onClose, onSaved }) {
  const employees = useEmployees();
  const now = new Date();
  const [form, setForm] = useState({ employeeId: '', month: now.getMonth() + 1, year: now.getFullYear(), bonus: 0, lopDays: 0 });
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));

  const save = async () => {
    setBusy(true); setErr('');
    try {
      await payApi.generate({
        employee_id: form.employeeId, month: Number(form.month), year: Number(form.year),
        bonus: Number(form.bonus), lop_days: Number(form.lopDays),
      });
      onSaved();
    } catch (e) { setErr(e.message || 'Could not generate payroll'); }
    finally { setBusy(false); }
  };

  return (
    <Modal open onClose={onClose} title="Generate payroll"
      footer={<><button className="btn-outline" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy || !form.employeeId} onClick={save}>{busy ? 'Generating…' : 'Generate'}</button></>}>
      {err && <div className="mb-4 rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{err}</div>}
      <div className="grid gap-4">
        <div>
          <label className="label">Employee</label>
          <select className="input" value={form.employeeId} onChange={set('employeeId')}>
            <option value="">— select —</option>
            {employees.map((e) => <option key={e._id} value={e._id}>{e.firstName} {e.lastName} ({e.employeeId})</option>)}
          </select>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div><label className="label">Month</label>
            <select className="input" value={form.month} onChange={set('month')}>{MONTHS.map((m, i) => <option key={m} value={i + 1}>{m}</option>)}</select>
          </div>
          <div><label className="label">Year</label><input className="input" type="number" value={form.year} onChange={set('year')} /></div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div><label className="label">Bonus</label><input className="input" type="number" value={form.bonus} onChange={set('bonus')} /></div>
          <div><label className="label">Loss-of-pay days</label><input className="input" type="number" value={form.lopDays} onChange={set('lopDays')} /></div>
        </div>
        <p className="text-xs text-slate-400">Tax is computed from the employee's salary-structure slabs. Set a structure first if none exists.</p>
      </div>
    </Modal>
  );
}

function StructureEditor({ onClose }) {
  const { user } = useAuth();
  const employees = useEmployees();
  const [employeeId, setEmployeeId] = useState('');
  const [form, setForm] = useState({ basic: 0, currency: 'USD', allowances: [], deductions: [], taxSlabs: [] });
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState('');

  useEffect(() => {
    if (!employeeId) return;
    payApi.getStructure(employeeId).then((s) => {
      if (s) setForm({ basic: s.basic, currency: s.currency || 'USD', allowances: s.allowances || [], deductions: s.deductions || [], taxSlabs: s.taxSlabs || [] });
      else setForm({ basic: 0, currency: 'USD', allowances: [], deductions: [], taxSlabs: [] });
    }).catch(() => {});
  }, [employeeId]);

  const addRow = (key, row) => setForm((f) => ({ ...f, [key]: [...f[key], row] }));
  const setRow = (key, i, patch) => setForm((f) => ({ ...f, [key]: f[key].map((r, idx) => idx === i ? { ...r, ...patch } : r) }));
  const delRow = (key, i) => setForm((f) => ({ ...f, [key]: f[key].filter((_, idx) => idx !== i) }));

  const save = async () => {
    setBusy(true); setMsg('');
    try {
      await payApi.saveStructure(user.company, employeeId, {
        basic: Number(form.basic), currency: form.currency,
        allowances: form.allowances.map((a) => ({ label: a.label, amount: Number(a.amount) })),
        deductions: form.deductions.map((d) => ({ label: d.label, amount: Number(d.amount) })),
        taxSlabs: form.taxSlabs.map((t) => ({ upTo: Number(t.upTo), rate: Number(t.rate) })),
      });
      setMsg('Saved.');
    } catch (e) { setMsg(e.message || 'Could not save'); }
    finally { setBusy(false); }
  };

  const Section = ({ title, k, fields }) => (
    <div>
      <div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium">{title}</span>
        <button className="btn-ghost px-2 py-1 text-xs" onClick={() => addRow(k, fields.reduce((o, f) => ({ ...o, [f]: '' }), {}))}>+ Add</button></div>
      <div className="space-y-2">
        {form[k].map((row, i) => (
          <div key={i} className="flex gap-2">
            <input className="input" placeholder="Label" value={row.label || ''} onChange={(e) => setRow(k, i, { label: e.target.value })} />
            <input className="input w-32" type="number" placeholder={k === 'taxSlabs' ? 'rate %' : 'amount'} value={row.amount ?? row.rate ?? ''} onChange={(e) => setRow(k, i, k === 'taxSlabs' ? { rate: e.target.value } : { amount: e.target.value })} />
            {k === 'taxSlabs' && <input className="input w-32" type="number" placeholder="up to" value={row.upTo ?? ''} onChange={(e) => setRow(k, i, { upTo: e.target.value })} />}
            <button className="btn-ghost px-2 text-rose-500" onClick={() => delRow(k, i)}>×</button>
          </div>
        ))}
        {form[k].length === 0 && <p className="text-xs text-slate-400">None.</p>}
      </div>
    </div>
  );

  return (
    <Modal open onClose={onClose} title="Salary structure" width="max-w-2xl"
      footer={<><button className="btn-outline" onClick={onClose}>Close</button><button className="btn-primary" disabled={busy || !employeeId} onClick={save}>{busy ? 'Saving…' : 'Save structure'}</button></>}>
      <div className="space-y-5">
        <div>
          <label className="label">Employee</label>
          <select className="input" value={employeeId} onChange={(e) => setEmployeeId(e.target.value)}>
            <option value="">— select —</option>
            {employees.map((e) => <option key={e._id} value={e._id}>{e.firstName} {e.lastName} ({e.employeeId})</option>)}
          </select>
        </div>
        {employeeId && (
          <>
            <div className="grid grid-cols-2 gap-4">
              <div><label className="label">Basic salary</label><input className="input" type="number" value={form.basic} onChange={(e) => setForm((f) => ({ ...f, basic: e.target.value }))} /></div>
              <div><label className="label">Currency</label><select className="input" value={form.currency} onChange={(e) => setForm((f) => ({ ...f, currency: e.target.value }))}>{['INR', 'USD', 'EUR', 'GBP', 'AED', 'SGD', 'AUD', 'CAD'].map((c) => <option key={c} value={c}>{c}</option>)}</select></div>
            </div>
            <Section title="Allowances" k="allowances" fields={['label', 'amount']} />
            <Section title="Deductions" k="deductions" fields={['label', 'amount']} />
            <Section title="Tax slabs (progressive)" k="taxSlabs" fields={['upTo', 'rate']} />
            {msg && <div className="rounded-xl bg-slate-100 px-3 py-2 text-sm dark:bg-slate-800">{msg}</div>}
          </>
        )}
      </div>
    </Modal>
  );
}
